#pragma once

enum EVENT : uint8_t 
{ 
	SUCCESS = 1, 
	CONTAINER_EMPTY,
	ELEMENT_NOT_FOUND,
	ELEMENT_EXCEED_LIMIT,
	PASSWORD_ERROR,
	ACCOUNT_ALREADY_EXIST,
	RECEIVER_EQUAL_SENDER,
	SENDER_NOT_EXIST,
	RECEIVER_NOT_EXIST,
	EXPRESS_UNKNOWN_KIND,
	BALANCE_NOT_ENOUGH,
	EXPRESS_ALREADY_PICKUP,
	EXPRESS_ALREADY_ASSIGN,
	EXPRESS_ALREADY_SIGNFOR,
	EXPRESS_FORBIT_SIGNFOR,
	ITEM_NOT_BELONG_TO_YOU
};
